//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 18/06/2024 07:59:08 p. m.
namespace CleanShopServer.Models.CleanShopDb
{
    /// <summary>
    /// There are no comments for ProductoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ProductoSingle")]
    public partial class ProductoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Producto>
    {
        /// <summary>
        /// Initialize a new ProductoSingle object.
        /// </summary>
        public ProductoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ProductoSingle object.
        /// </summary>
        public ProductoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ProductoSingle object.
        /// </summary>
        public ProductoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Producto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Ventas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ventas")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Venta> Ventas
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Ventas == null))
                {
                    this._Ventas = Context.CreateQuery<global::CleanShopServer.Models.CleanShopDb.Venta>(GetPath("Ventas"));
                }
                return this._Ventas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Venta> _Ventas;
    }
    /// <summary>
    /// There are no comments for Producto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdProductos
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("IdProductos")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Producto")]
    public partial class Producto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Producto object.
        /// </summary>
        /// <param name="idProductos">Initial value of IdProductos.</param>
        /// <param name="titulo">Initial value of Titulo.</param>
        /// <param name="precioUnitario">Initial value of PrecioUnitario.</param>
        /// <param name="existencias">Initial value of Existencias.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Producto CreateProducto(int idProductos, string titulo, decimal precioUnitario, int existencias)
        {
            Producto producto = new Producto();
            producto.IdProductos = idProductos;
            producto.Titulo = titulo;
            producto.PrecioUnitario = precioUnitario;
            producto.Existencias = existencias;
            return producto;
        }
        /// <summary>
        /// There are no comments for Property IdProductos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IdProductos")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IdProductos is required.")]
        public virtual int IdProductos
        {
            get
            {
                return this._IdProductos;
            }
            set
            {
                this.OnIdProductosChanging(value);
                this._IdProductos = value;
                this.OnIdProductosChanged();
                this.OnPropertyChanged("IdProductos");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _IdProductos;
        partial void OnIdProductosChanging(int value);
        partial void OnIdProductosChanged();
        /// <summary>
        /// There are no comments for Property Titulo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Titulo")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Titulo is required.")]
        public virtual string Titulo
        {
            get
            {
                return this._Titulo;
            }
            set
            {
                this.OnTituloChanging(value);
                this._Titulo = value;
                this.OnTituloChanged();
                this.OnPropertyChanged("Titulo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Titulo;
        partial void OnTituloChanging(string value);
        partial void OnTituloChanged();
        /// <summary>
        /// There are no comments for Property Descripcion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Descripcion")]
        public virtual string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this.OnDescripcionChanging(value);
                this._Descripcion = value;
                this.OnDescripcionChanged();
                this.OnPropertyChanged("Descripcion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Descripcion;
        partial void OnDescripcionChanging(string value);
        partial void OnDescripcionChanged();
        /// <summary>
        /// There are no comments for Property PrecioUnitario in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PrecioUnitario")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PrecioUnitario is required.")]
        public virtual decimal PrecioUnitario
        {
            get
            {
                return this._PrecioUnitario;
            }
            set
            {
                this.OnPrecioUnitarioChanging(value);
                this._PrecioUnitario = value;
                this.OnPrecioUnitarioChanged();
                this.OnPropertyChanged("PrecioUnitario");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private decimal _PrecioUnitario;
        partial void OnPrecioUnitarioChanging(decimal value);
        partial void OnPrecioUnitarioChanged();
        /// <summary>
        /// There are no comments for Property Existencias in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Existencias")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Existencias is required.")]
        public virtual int Existencias
        {
            get
            {
                return this._Existencias;
            }
            set
            {
                this.OnExistenciasChanging(value);
                this._Existencias = value;
                this.OnExistenciasChanged();
                this.OnPropertyChanged("Existencias");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Existencias;
        partial void OnExistenciasChanging(int value);
        partial void OnExistenciasChanged();
        /// <summary>
        /// There are no comments for Property Ventas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Ventas")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::CleanShopServer.Models.CleanShopDb.Venta> Ventas
        {
            get
            {
                return this._Ventas;
            }
            set
            {
                this.OnVentasChanging(value);
                this._Ventas = value;
                this.OnVentasChanged();
                this.OnPropertyChanged("Ventas");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::CleanShopServer.Models.CleanShopDb.Venta> _Ventas = new global::Microsoft.OData.Client.DataServiceCollection<global::CleanShopServer.Models.CleanShopDb.Venta>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnVentasChanging(global::Microsoft.OData.Client.DataServiceCollection<global::CleanShopServer.Models.CleanShopDb.Venta> value);
        partial void OnVentasChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for VentaSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("VentaSingle")]
    public partial class VentaSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Venta>
    {
        /// <summary>
        /// Initialize a new VentaSingle object.
        /// </summary>
        public VentaSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new VentaSingle object.
        /// </summary>
        public VentaSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new VentaSingle object.
        /// </summary>
        public VentaSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Venta> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Producto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Producto")]
        public virtual global::CleanShopServer.Models.CleanShopDb.ProductoSingle Producto
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Producto == null))
                {
                    this._Producto = new global::CleanShopServer.Models.CleanShopDb.ProductoSingle(this.Context, GetPath("Producto"));
                }
                return this._Producto;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::CleanShopServer.Models.CleanShopDb.ProductoSingle _Producto;
    }
    /// <summary>
    /// There are no comments for Venta in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdVentas
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("IdVentas")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Venta")]
    public partial class Venta : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Venta object.
        /// </summary>
        /// <param name="idVentas">Initial value of IdVentas.</param>
        /// <param name="fecha">Initial value of Fecha.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Venta CreateVenta(int idVentas, global::System.DateTimeOffset fecha)
        {
            Venta venta = new Venta();
            venta.IdVentas = idVentas;
            venta.Fecha = fecha;
            return venta;
        }
        /// <summary>
        /// There are no comments for Property IdVentas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IdVentas")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "IdVentas is required.")]
        public virtual int IdVentas
        {
            get
            {
                return this._IdVentas;
            }
            set
            {
                this.OnIdVentasChanging(value);
                this._IdVentas = value;
                this.OnIdVentasChanged();
                this.OnPropertyChanged("IdVentas");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _IdVentas;
        partial void OnIdVentasChanging(int value);
        partial void OnIdVentasChanged();
        /// <summary>
        /// There are no comments for Property Idproductos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Idproductos")]
        public virtual global::System.Nullable<int> Idproductos
        {
            get
            {
                return this._Idproductos;
            }
            set
            {
                this.OnIdproductosChanging(value);
                this._Idproductos = value;
                this.OnIdproductosChanged();
                this.OnPropertyChanged("Idproductos");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Idproductos;
        partial void OnIdproductosChanging(global::System.Nullable<int> value);
        partial void OnIdproductosChanged();
        /// <summary>
        /// There are no comments for Property CantidadVendida in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CantidadVendida")]
        public virtual global::System.Nullable<int> CantidadVendida
        {
            get
            {
                return this._CantidadVendida;
            }
            set
            {
                this.OnCantidadVendidaChanging(value);
                this._CantidadVendida = value;
                this.OnCantidadVendidaChanged();
                this.OnPropertyChanged("CantidadVendida");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CantidadVendida;
        partial void OnCantidadVendidaChanging(global::System.Nullable<int> value);
        partial void OnCantidadVendidaChanged();
        /// <summary>
        /// There are no comments for Property Fecha in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Fecha")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Fecha is required.")]
        public virtual global::System.DateTimeOffset Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this.OnFechaChanging(value);
                this._Fecha = value;
                this.OnFechaChanged();
                this.OnPropertyChanged("Fecha");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _Fecha;
        partial void OnFechaChanging(global::System.DateTimeOffset value);
        partial void OnFechaChanged();
        /// <summary>
        /// There are no comments for Property Producto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Producto")]
        public virtual global::CleanShopServer.Models.CleanShopDb.Producto Producto
        {
            get
            {
                return this._Producto;
            }
            set
            {
                this.OnProductoChanging(value);
                this._Producto = value;
                this.OnProductoChanged();
                this.OnPropertyChanged("Producto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::CleanShopServer.Models.CleanShopDb.Producto _Producto;
        partial void OnProductoChanging(global::CleanShopServer.Models.CleanShopDb.Producto value);
        partial void OnProductoChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::CleanShopServer.Models.CleanShopDb.Producto as global::CleanShopServer.Models.CleanShopDb.ProductoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::CleanShopServer.Models.CleanShopDb.ProductoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Producto> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::CleanShopServer.Models.CleanShopDb.ProductoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::CleanShopServer.Models.CleanShopDb.Producto as global::CleanShopServer.Models.CleanShopDb.ProductoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="idProductos">The value of idProductos</param>
        public static global::CleanShopServer.Models.CleanShopDb.ProductoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Producto> _source,
            int idProductos)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "IdProductos", idProductos }
            };
            return new global::CleanShopServer.Models.CleanShopDb.ProductoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::CleanShopServer.Models.CleanShopDb.Venta as global::CleanShopServer.Models.CleanShopDb.VentaSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::CleanShopServer.Models.CleanShopDb.VentaSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Venta> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::CleanShopServer.Models.CleanShopDb.VentaSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::CleanShopServer.Models.CleanShopDb.Venta as global::CleanShopServer.Models.CleanShopDb.VentaSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="idVentas">The value of idVentas</param>
        public static global::CleanShopServer.Models.CleanShopDb.VentaSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Venta> _source,
            int idVentas)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "IdVentas", idVentas }
            };
            return new global::CleanShopServer.Models.CleanShopDb.VentaSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "CleanShopServer.Models.CleanShopDb", "CleanShopServer.Models.CleanShopDb");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("CleanShopServer.Models.CleanShopDb", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("CleanShopServer.Models.CleanShopDb.", originalNameAttribute.OriginalName);
                }
                return string.Concat("CleanShopServer.Models.CleanShopDb.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Productos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Productos")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Producto> Productos
        {
            get
            {
                if ((this._Productos == null))
                {
                    this._Productos = base.CreateQuery<global::CleanShopServer.Models.CleanShopDb.Producto>("Productos");
                }
                return this._Productos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Producto> _Productos;
        /// <summary>
        /// There are no comments for Ventas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ventas")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Venta> Ventas
        {
            get
            {
                if ((this._Ventas == null))
                {
                    this._Ventas = base.CreateQuery<global::CleanShopServer.Models.CleanShopDb.Venta>("Ventas");
                }
                return this._Ventas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::CleanShopServer.Models.CleanShopDb.Venta> _Ventas;
        /// <summary>
        /// There are no comments for Productos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToProductos(global::CleanShopServer.Models.CleanShopDb.Producto producto)
        {
            base.AddObject("Productos", producto);
        }
        /// <summary>
        /// There are no comments for Ventas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToVentas(global::CleanShopServer.Models.CleanShopDb.Venta venta)
        {
            base.AddObject("Ventas", venta);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"CleanShopODataServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
